### ISSUE TITLE
旋转算法有问题

### ISSUE THREAD

**Issue by zhangliangming** [ChanJLee/ChanKugouLayout#1]
看了楼主的思路，我觉得楼主在选择旋转的中心点时，应该是选择错了，我觉得酷狗的中心旋转点，应该是在X= width * 0.5f，Y = height * 1.5f。然后根据第一次的触摸点，根据楼主的算法获取第一次触摸点的角度 A（如果角度为负数，则A = A+180），同理再试算最后一次的触摸点角度 B（如果角度为负数，则B = B+180）。最后，计算旋转的角度 D = B - A。即可

**Comment by zhangliangming** [comment]
我因为是参考ios的，所以。。。。。

**Comment by ChanJLee** [comment]
...
